<?php
/**
 * English dictionary for hit-sbom-import extension
 */

Dict::Add('EN US', 'English', 'English', array(

	// ---- SBOMComponent ----
	'Class:SBOMComponent'                                    => 'SBOM Component',
	'Class:SBOMComponent+'                                   => 'A software package or library recorded in a CycloneDX Software Bill of Materials',
	'Class:SBOMComponent/Attribute:name'                     => 'Name',
	'Class:SBOMComponent/Attribute:name+'                    => 'Package name',
	'Class:SBOMComponent/Attribute:version'                  => 'Version',
	'Class:SBOMComponent/Attribute:version+'                 => 'Package version string',
	'Class:SBOMComponent/Attribute:purl'                     => 'Package URL (purl)',
	'Class:SBOMComponent/Attribute:purl+'                    => 'Globally unique package URL (e.g. pkg:npm/lodash@4.17.21)',
	'Class:SBOMComponent/Attribute:cpe'                      => 'CPE',
	'Class:SBOMComponent/Attribute:cpe+'                     => 'Common Platform Enumeration identifier',
	'Class:SBOMComponent/Attribute:component_type'           => 'Type',
	'Class:SBOMComponent/Attribute:component_type+'          => 'CycloneDX component type',
	'Class:SBOMComponent/Attribute:component_type/Value:application'  => 'Application',
	'Class:SBOMComponent/Attribute:component_type/Value:library'      => 'Library',
	'Class:SBOMComponent/Attribute:component_type/Value:framework'    => 'Framework',
	'Class:SBOMComponent/Attribute:component_type/Value:container'    => 'Container',
	'Class:SBOMComponent/Attribute:component_type/Value:firmware'     => 'Firmware',
	'Class:SBOMComponent/Attribute:component_type/Value:device'       => 'Device',
	'Class:SBOMComponent/Attribute:component_type/Value:data'         => 'Data',
	'Class:SBOMComponent/Attribute:component_type/Value:file'         => 'File',
	'Class:SBOMComponent/Attribute:license_expression'       => 'License',
	'Class:SBOMComponent/Attribute:license_expression+'      => 'SPDX license expression (e.g. MIT, Apache-2.0)',
	'Class:SBOMComponent/Attribute:supplier_name'            => 'Supplier',
	'Class:SBOMComponent/Attribute:supplier_name+'           => 'Vendor or author name',
	'Class:SBOMComponent/Attribute:hash_sha256'              => 'SHA-256 Hash',
	'Class:SBOMComponent/Attribute:hash_sha256+'             => 'SHA-256 hash of the component artifact',
	'Class:SBOMComponent/Attribute:description'              => 'Description',
	'Class:SBOMComponent/Attribute:description+'             => '',
	'Class:SBOMComponent/Attribute:sbom_artifacts_list'      => 'SBOM Artifacts',
	'Class:SBOMComponent/Attribute:sbom_artifacts_list+'     => 'SBOMs that include this component',
	'Class:SBOMComponent/Attribute:dependencies_list'        => 'Depends On',
	'Class:SBOMComponent/Attribute:dependencies_list+'       => 'Components this component depends on',
	'Class:SBOMComponent/Attribute:dependents_list'          => 'Used By',
	'Class:SBOMComponent/Attribute:dependents_list+'         => 'Components that depend on this component',

	// ---- SBOMArtifact ----
	'Class:SBOMArtifact'                                     => 'SBOM Artifact',
	'Class:SBOMArtifact+'                                    => 'Primary software artifact described by a CycloneDX Software Bill of Materials',
	'Class:SBOMArtifact/Attribute:version'                   => 'Version',
	'Class:SBOMArtifact/Attribute:version+'                  => 'Artifact version string',
	'Class:SBOMArtifact/Attribute:purl'                      => 'Package URL (purl)',
	'Class:SBOMArtifact/Attribute:purl+'                     => 'Globally unique package URL',
	'Class:SBOMArtifact/Attribute:component_type'            => 'Type',
	'Class:SBOMArtifact/Attribute:component_type+'           => 'CycloneDX component type of the primary artifact',
	'Class:SBOMArtifact/Attribute:component_type/Value:application'  => 'Application',
	'Class:SBOMArtifact/Attribute:component_type/Value:library'      => 'Library',
	'Class:SBOMArtifact/Attribute:component_type/Value:framework'    => 'Framework',
	'Class:SBOMArtifact/Attribute:component_type/Value:container'    => 'Container',
	'Class:SBOMArtifact/Attribute:component_type/Value:firmware'     => 'Firmware',
	'Class:SBOMArtifact/Attribute:component_type/Value:device'       => 'Device',
	'Class:SBOMArtifact/Attribute:component_type/Value:data'         => 'Data',
	'Class:SBOMArtifact/Attribute:component_type/Value:file'         => 'File',
	'Class:SBOMArtifact/Attribute:cyclonedx_version'         => 'CycloneDX Version',
	'Class:SBOMArtifact/Attribute:cyclonedx_version+'        => 'CycloneDX spec version used in the SBOM file (e.g. 1.4, 1.5)',
	'Class:SBOMArtifact/Attribute:sbom_serial_number'        => 'BOM Serial Number',
	'Class:SBOMArtifact/Attribute:sbom_serial_number+'       => 'Unique serial number / URN UUID from the CycloneDX file',
	'Class:SBOMArtifact/Attribute:supplier_name'             => 'Supplier',
	'Class:SBOMArtifact/Attribute:supplier_name+'            => 'Vendor or author name',
	'Class:SBOMArtifact/Attribute:license_expression'        => 'License',
	'Class:SBOMArtifact/Attribute:license_expression+'       => 'SPDX license expression',
	'Class:SBOMArtifact/Attribute:functionalci_id'           => 'Linked CI',
	'Class:SBOMArtifact/Attribute:functionalci_id+'          => 'The Configuration Item (Application, Server, …) this SBOM describes',
	'Class:SBOMArtifact/Attribute:functionalci_name'         => 'Linked CI Name',
	'Class:SBOMArtifact/Attribute:functionalci_name+'        => '',
	'Class:SBOMArtifact/Attribute:components_list'           => 'Components',
	'Class:SBOMArtifact/Attribute:components_list+'          => 'All packages and libraries listed in this SBOM',

	// ---- FunctionalCI delta ----
	'Class:FunctionalCI/Attribute:sbom_artifacts_list'       => 'SBOM Artifacts',
	'Class:FunctionalCI/Attribute:sbom_artifacts_list+'      => 'Software Bills of Materials generated for this CI',

	// ---- lnkSBOMArtifactToSBOMComponent ----
	'Class:lnkSBOMArtifactToSBOMComponent'                              => 'SBOM Artifact / Component',
	'Class:lnkSBOMArtifactToSBOMComponent+'                             => 'Link between a SBOM artifact and one of its components',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:artifact_id'        => 'SBOM Artifact',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:artifact_id+'       => '',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:artifact_name'      => 'Artifact Name',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:artifact_name+'     => '',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:component_id'       => 'Component',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:component_id+'      => '',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:component_name'     => 'Component Name',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:component_name+'    => '',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:dependency_type'    => 'Dependency Type',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:dependency_type+'   => 'Whether this is a direct or transitive dependency',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:dependency_type/Value:direct'     => 'Direct',
	'Class:lnkSBOMArtifactToSBOMComponent/Attribute:dependency_type/Value:transitive' => 'Transitive',

	// ---- Import page UI strings ----
	'UI:SBOM:ImportTitle'              => 'CycloneDX SBOM Import',
	'UI:SBOM:ImportSuccess'            => 'Import completed successfully',
	'UI:SBOM:Artifact'                 => 'Artifact',
	'UI:SBOM:ComponentsCreated'        => 'New components created',
	'UI:SBOM:ComponentsReused'         => 'Existing components reused',
	'UI:SBOM:DepEdges'                 => 'Dependency edges created',
	'UI:SBOM:Warnings'                 => 'Warnings',
	'UI:SBOM:BackToList'               => 'Back to SBOM Artifacts list',
	'UI:SBOM:Form:Step1'               => 'Step 1 — Select target',
	'UI:SBOM:Form:Step2'               => 'Step 2 — Upload SBOM file',
	'UI:SBOM:Form:FunctionalCIHelp'    => 'Optional — the Application / Server / CI this SBOM was generated for',
	'UI:SBOM:Form:FileHelp'            => 'Accepted formats: CycloneDX JSON (.json) or CycloneDX XML (.xml)',
	'UI:SBOM:Form:Submit'              => 'Import SBOM',
	'UI:SBOM:Error:OrgRequired'        => 'Please select an Organisation before importing.',
	'UI:SBOM:Error:FileRequired'       => 'Please select a valid SBOM file to upload.',
	'UI:SBOM:Error:UnsupportedFormat'  => 'Unsupported file extension "%s". Use .json or .xml.',
	'UI:SBOM:Error:ImportFailed'       => 'Import failed:',

	// ---- Impact Analysis page UI strings ----
	'UI:SBOM:ImpactAnalysis'           => 'SBOM Impact Analysis',
	'UI:SBOM:ImpactSelectHelp'         => 'Select an SBOM Component or Artifact and choose a direction to view the impact graph.',
	'UI:SBOM:ImpactClass'              => 'Class',
	'UI:SBOM:ImpactObjectId'           => 'Object ID',
	'UI:SBOM:ImpactDirection'          => 'Direction',
	'UI:SBOM:ImpactDirection:Down'     => 'Impacts (downstream)',
	'UI:SBOM:ImpactDirection:Up'       => 'Depends on (upstream)',
	'UI:SBOM:ImpactShow'               => 'Show Impact Graph',

	// ---- SBOMComponent status enum ----
	'Class:SBOMComponent/Attribute:status'                   => 'Status',
	'Class:SBOMComponent/Attribute:status+'                  => '',
	'Class:SBOMComponent/Attribute:status/Value:active'      => 'Active',
	'Class:SBOMComponent/Attribute:status/Value:deprecated'  => 'Deprecated',
	'Class:SBOMComponent/Attribute:status/Value:obsolete'    => 'Obsolete',

	// ---- SBOMArtifact status enum ----
	'Class:SBOMArtifact/Attribute:status'                    => 'Status',
	'Class:SBOMArtifact/Attribute:status+'                   => '',
	'Class:SBOMArtifact/Attribute:status/Value:active'       => 'Active',
	'Class:SBOMArtifact/Attribute:status/Value:archived'     => 'Archived',
	'Class:SBOMArtifact/Attribute:status/Value:obsolete'     => 'Obsolete',

	// ---- lnkSBOMComponentToSBOMComponent ----
	'Class:lnkSBOMComponentToSBOMComponent'                                => 'Component Dependency',
	'Class:lnkSBOMComponentToSBOMComponent+'                               => 'Directed dependency edge between two SBOM components',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependent_id'         => 'Dependent',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependent_id+'        => 'The component that has the dependency',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependent_name'       => 'Dependent Name',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependent_name+'      => '',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependency_id'        => 'Dependency',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependency_id+'       => 'The component that is depended upon',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependency_name'      => 'Dependency Name',
	'Class:lnkSBOMComponentToSBOMComponent/Attribute:dependency_name+'     => '',
));
